name: flake 

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7","3.6","3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run test
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
        pytest -v test/ --junitxml=test-reports/report.xml
    - name: Run flake8 
      run: |
        pip install flake8
        flake8 . --extend-exclude=dist,build,venv,barq/logo.py --show-source --statistics
